# yaml-language-server: $schema=https://github.com/epics-containers/ioc-template-example/releases/download/3.5.1/ibek.ioc.schema.json

# TODO replace above with the generic IOC schema this IOC is based on
ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: REPLACE WITH DESCRIPTION

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TZ
    value: GMT0BST

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"


  - type: epics.EpicsEnvSet
    name: EPICS_TS_MIN_WEST
    value: '0'
    
  - type: epics.EpicsCaMaxArrayBytes
    max_bytes: 9000000

  - type: ADAndor.andorCCD
    ADDR: 0
    BUFFERS: 2000
    INSTALLPATH: /dls_sw/prod/R3.14.12.7/support/ANAndor/etc
    P: BL99P-EA-DET-03
    PORT: DET3.cam
    R: ':CAM:'
    TIMEOUT: 1

  - type: ADCore.NDPosPlugin
    ADDR: 0
    BLOCK: 0
    ENABLED: 1
    NDARRAY_PORT: DET3.cam
    P: BL99P-EA-DET-03
    PORT: DET3.pos
    QUEUE: 1000
    R: ':POS:'
    TIMEOUT: 1

  - type: ADCore.NDROI
    ADDR: 0
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET3.cam
    P: BL99P-EA-DET-03
    PORT: DET3.roi
    QUEUE: 1000
    R: ':ROI:'
    TIMEOUT: 1

  - type: ADCore.NDStats
    ADDR: 0
    HIST_SIZE: 256
    NCHANS: 20000
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET3.cam
    P: BL99P-EA-DET-03
    PORT: DET3.stat
    QUEUE: 1000
    R: ':STAT:'
    TIMEOUT: 1
    XSIZE: 1024
    YSIZE: 768

  - type: ADCore.NDStdArrays
    ADDR: 0
    FTVL: USHORT
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET3.roi
    NELEMENTS: 786432
    P: BL99P-EA-DET-03
    PORT: DET3.arr
    QUEUE: 2
    R: ':ARR:'
    TIMEOUT: 1
    TYPE: Int16

  - type: ADCore.NDProcess
    ADDR: 0
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET3.cam
    P: BL99P-EA-DET-03
    PORT: DET3.proc
    QUEUE: 1000
    R: ':PROC:'
    TIMEOUT: 1

  - type: ADCore.NDOverlay
    ADDR: 0
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET3.proc
    P: BL99P-EA-DET-03
    PORT: DET3.over
    QUEUE: 1000
    R: ':OVER:'
    TIMEOUT: 1

  - type: ADCore.NDFileTIFF
    ADDR: 0
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET3.cam
    P: BL99P-EA-DET-03
    PORT: DET3.tiff
    QUEUE: 1000
    R: ':TIFF:'
    TIMEOUT: 1

  - type: ADCore.NDFileHDF5
    ADDR: 0
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET3.cam
    P: BL99P-EA-DET-03
    PORT: DET3.hdf
    QUEUE: 1000
    R: ':HDF5:'
    TIMEOUT: 1