# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.0.0
_src_path: gh:epics-containers/ioc-template
description: 'The Generic IOC for the adandor '
git_platform: github.com
github_org: MaxHerbs
name: ioc-adandor
repo_uri: git@github.com:MaxHerbs/ioc-adandor.git
rtems: false
